url: ""
baseurl: ""
title: "ClarkThyLord"

github_rep: "https://github.com/ClarkThyLord/ClarkThyLord.github.io"

twitter: "ClarkThyLord"
github: "ClarkThyLord"
youtube: "ClarkThyLord"
youtube_id: "UCJuo4Y8b-YT46mHBLz7zt0g"
reddit: "ClarkThyLord"
linkedin: "ClarkThyLord"
twitch: "ClarkThyLord"
discord: "ClarkThyLord#7042"
mail: "ccpotential@gmail.com"


exclude:
  - README.md
